import type { Metadata } from "next";

import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["400", "700"], // Tentukan berat font yang ingin Anda gunakan
});

import "@/components/sass/globals.scss";

import "@/components/sass/layout.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import dynamic from "next/dynamic";

const Navbar = dynamic(() => import("@/components/UI/layout/Navbar"), {
  ssr: false,
});
const Header = dynamic(() => import("@/components/UI/layout/Header"), {
  ssr: false,
});
const Footer = dynamic(() => import("@/components/UI/layout/Footer"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Navbar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
